# Traefik konfigurace pro domácí server
# Použití hostNetwork pro přímý přístup na porty 80/443
hostNetwork: true

service:
  type: ClusterIP

# Porty pro hostNetwork
ports:
  web:
    port: 80
    hostPort: 80
  websecure:
    port: 443
    hostPort: 443
  traefik:
    port: 9000
    hostPort: 9000

# Bezpečnostní kontext pro privilegovaný přístup k portům
securityContext:
  capabilities:
    add:
      - NET_BIND_SERVICE
  runAsNonRoot: false
  runAsUser: 0

# Globální argumenty pro HTTPS redirect
globalArguments:
  - "--global.checknewversion=false"
  - "--global.sendanonymoususage=false"
  - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
  - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

# Povolení dashboard
api:
  dashboard: true
  insecure: true

# Providers
providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

# Tolerations pro master node
tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
